"""Seed data for TheHopper karaoke app.

Realistic mock data for Brevard County, FL venues and a curated karaoke song database
with vocal range / difficulty metadata.
"""

# ---------------------------------------------------------------------------
# Venues — Brevard County, FL (Cocoa Beach, Melbourne, Palm Bay, Titusville,
# Rockledge, Viera, Satellite Beach, Indian Harbour Beach, Cape Canaveral)
# Coordinates are approximate real-world lat/lon for those cities.
# ---------------------------------------------------------------------------

VENUES = [
    {
        "name": "Coconuts on the Beach",
        "address": "2 Minutemen Causeway, Cocoa Beach, FL 32931",
        "city": "Cocoa Beach",
        "lat": 28.3200,
        "lng": -80.6070,
        "karaoke_nights": ["Wednesday", "Saturday"],
        "start_time": "20:00",
        "end_time": "01:00",
        "kj_name": "DJ Salty Mike",
        "phone": "(321) 555-0142",
        "website": "https://example.com/coconuts",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "Beach bar, divey, loud, packed on weekends.",
    },
    {
        "name": "Lou's Blues Upstairs",
        "address": "1661 Atlantic Ave, Cocoa Beach, FL 32931",
        "city": "Cocoa Beach",
        "lat": 28.3390,
        "lng": -80.6090,
        "karaoke_nights": ["Thursday", "Sunday"],
        "start_time": "21:00",
        "end_time": "02:00",
        "kj_name": "Roxi Heart",
        "phone": "(321) 555-0177",
        "website": "https://example.com/lous",
        "price_jump_queue": 7.00,
        "premium_slot_position": 4,
        "premium_slot_price": 7.00,
        "vibe": "Live-music bar, intimate stage, great sound system.",
    },
    {
        "name": "Cocoa Beach Pier Saloon",
        "address": "401 Meade Ave, Cocoa Beach, FL 32931",
        "city": "Cocoa Beach",
        "lat": 28.3680,
        "lng": -80.5980,
        "karaoke_nights": ["Friday", "Saturday"],
        "start_time": "19:00",
        "end_time": "00:00",
        "kj_name": "Tommy Tunes",
        "phone": "(321) 555-0188",
        "website": "https://example.com/pier",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "Tourist spot on the pier, sunset views, casual crowd.",
    },
    {
        "name": "Meg O'Malley's",
        "address": "812 E New Haven Ave, Melbourne, FL 32901",
        "city": "Melbourne",
        "lat": 28.0810,
        "lng": -80.6050,
        "karaoke_nights": ["Tuesday", "Sunday"],
        "start_time": "20:30",
        "end_time": "01:30",
        "kj_name": "Meg herself",
        "phone": "(321) 555-0201",
        "website": "https://example.com/megomalleys",
        "price_jump_queue": 6.00,
        "premium_slot_position": 3,
        "premium_slot_price": 6.00,
        "vibe": "Irish pub, decent food, big screens, friendly regulars.",
    },
    {
        "name": "Palm Bay Pub & Grill",
        "address": "1300 Malabar Rd SE, Palm Bay, FL 32950",
        "city": "Palm Bay",
        "lat": 28.0240,
        "lng": -80.6470,
        "karaoke_nights": ["Wednesday", "Saturday"],
        "start_time": "21:00",
        "end_time": "01:00",
        "kj_name": "DJ Crystal",
        "phone": "(321) 555-0215",
        "website": "https://example.com/palmbaypub",
        "price_jump_queue": 4.00,
        "premium_slot_position": 2,
        "premium_slot_price": 4.00,
        "vibe": "Neighborhood sports bar, pool tables, decent stage.",
    },
    {
        "name": "Slow & Low Bar-B-Que",
        "address": "1905 S Harbor City Blvd, Melbourne, FL 32901",
        "city": "Melbourne",
        "lat": 28.0620,
        "lng": -80.6140,
        "karaoke_nights": ["Friday"],
        "start_time": "19:30",
        "end_time": "23:30",
        "kj_name": "BBQ Bob",
        "phone": "(321) 555-0233",
        "website": "https://example.com/slowandlow",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "BBQ joint turns into a rowdy singalong after 8pm.",
    },
    {
        "name": "Dogz Beef & Brewhouse",
        "address": "405 S Apollo Blvd, Melbourne, FL 32935",
        "city": "Melbourne",
        "lat": 28.1040,
        "lng": -80.6280,
        "karaoke_nights": ["Tuesday", "Thursday"],
        "start_time": "20:00",
        "end_time": "00:00",
        "kj_name": "Hank the Host",
        "phone": "(321) 555-0244",
        "website": "https://example.com/dogz",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "Hot dog + beer joint, college crowd, cheap drinks.",
    },
    {
        "name": "Pig & Whistle Tavern",
        "address": "5250 N Wickham Rd, Viera, FL 32940",
        "city": "Viera",
        "lat": 28.2330,
        "lng": -80.7270,
        "karaoke_nights": ["Wednesday", "Sunday"],
        "start_time": "21:00",
        "end_time": "01:00",
        "kj_name": "Tavvy Tom",
        "phone": "(321) 555-0256",
        "website": "https://example.com/pigwhistle",
        "price_jump_queue": 6.00,
        "premium_slot_position": 4,
        "premium_slot_price": 6.00,
        "vibe": "British pub in Viera's upscale plaza, older crowd, refined stage.",
    },
    {
        "name": "Playalinda Brewing Co.",
        "address": "320 Washington Ave, Titusville, FL 32780",
        "city": "Titusville",
        "lat": 28.6120,
        "lng": -80.8190,
        "karaoke_nights": ["Thursday", "Saturday"],
        "start_time": "20:00",
        "end_time": "00:00",
        "kj_name": "Suds Samantha",
        "phone": "(321) 555-0267",
        "website": "https://example.com/playalinda",
        "price_jump_queue": 7.00,
        "premium_slot_position": 3,
        "premium_slot_price": 7.00,
        "vibe": "Craft brewery in downtown Titusville, rocket-launch-viewing rooftop.",
    },
    {
        "name": "Satellite Beach Sportsbar",
        "address": "777 S Patrick Dr, Satellite Beach, FL 32937",
        "city": "Satellite Beach",
        "lat": 28.1790,
        "lng": -80.5990,
        "karaoke_nights": ["Monday", "Friday"],
        "start_time": "21:00",
        "end_time": "01:00",
        "kj_name": "DJ Skip",
        "phone": "(321) 555-0278",
        "website": "https://example.com/satbeach",
        "price_jump_queue": 4.00,
        "premium_slot_position": 2,
        "premium_slot_price": 4.00,
        "vibe": "Beachside sports bar, patio stage, surfers & retirees mixed crowd.",
    },
    {
        "name": "Indian Harbour Brewhaus",
        "address": "465 S Wickham Rd, Indian Harbour Beach, FL 32937",
        "city": "Indian Harbour Beach",
        "lat": 28.1530,
        "lng": -80.6630,
        "karaoke_nights": ["Tuesday", "Saturday"],
        "start_time": "20:30",
        "end_time": "00:30",
        "kj_name": "Brew Barrymore",
        "phone": "(321) 555-0289",
        "website": "https://example.com/ihbrewhaus",
        "price_jump_queue": 6.00,
        "premium_slot_position": 3,
        "premium_slot_price": 6.00,
        "vibe": "Local nano-brewery, chill vibe, patio karaoke.",
    },
    {
        "name": "Canaveral Pier House",
        "address": "5000 Ocean Beach Blvd, Cape Canaveral, FL 32920",
        "city": "Cape Canaveral",
        "lat": 28.3920,
        "lng": -80.5990,
        "karaoke_nights": ["Friday", "Sunday"],
        "start_time": "21:00",
        "end_time": "02:00",
        "kj_name": "Captain Carla",
        "phone": "(321) 555-0290",
        "website": "https://example.com/canaveralpier",
        "price_jump_queue": 8.00,
        "premium_slot_position": 5,
        "premium_slot_price": 8.00,
        "vibe": "Cruise-port-adjacent bar, big tourist crowd, high-energy karaoke.",
    },
    {
        "name": "Rockledge Taproom",
        "address": "220 Barton Blvd, Rockledge, FL 32955",
        "city": "Rockledge",
        "lat": 28.2650,
        "lng": -80.7240,
        "karaoke_nights": ["Wednesday", "Saturday"],
        "start_time": "20:00",
        "end_time": "01:00",
        "kj_name": "Rocky Rhodes",
        "phone": "(321) 555-0301",
        "website": "https://example.com/rockledgetap",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "Industrial-chic taproom with a small but loyal karaoke following.",
    },
    {
        "name": "Bayside Lakes Lounge",
        "address": "1190 Malabar Rd SE, Palm Bay, FL 32909",
        "city": "Palm Bay",
        "lat": 27.9900,
        "lng": -80.6320,
        "karaoke_nights": ["Thursday", "Sunday"],
        "start_time": "21:00",
        "end_time": "01:00",
        "kj_name": "Lakeshore Larry",
        "phone": "(321) 555-0312",
        "website": "https://example.com/bayside",
        "price_jump_queue": 5.00,
        "premium_slot_position": 3,
        "premium_slot_price": 5.00,
        "vibe": "Suburban lounge, dance floor, mostly locals.",
    },
    {
        "name": "The Twisted Owl",
        "address": "1400 W Eau Gallie Blvd, Melbourne, FL 32935",
        "city": "Melbourne",
        "lat": 28.1320,
        "lng": -80.6510,
        "karaoke_nights": ["Monday", "Thursday"],
        "start_time": "20:00",
        "end_time": "00:00",
        "kj_name": "Hoot Hannah",
        "phone": "(321) 555-0323",
        "website": "https://example.com/twistedowl",
        "price_jump_queue": 4.00,
        "premium_slot_position": 2,
        "premium_slot_price": 4.00,
        "vibe": "Dive bar with attitude, cheap pitchers, surprisingly good songbook.",
    },
]


# ---------------------------------------------------------------------------
# Songs — 60 popular karaoke songs with vocal-range fit and difficulty.
# difficulty: 1 (easy) .. 5 (killer, wide range / sustained belts)
# range_fit: list of vocal ranges this song suits well
#   bass / baritone / tenor / alto / mezzo / soprano
# genre: broad tag for style matching
# year, artist, title
# ---------------------------------------------------------------------------

SONGS = [
    # --- Classic rock & arena anthems ---
    {
        "title": "Don't Stop Believin'",
        "artist": "Journey",
        "genre": "Rock",
        "year": 1981,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "soprano"],
        "notes": "That final '...streetlight people' climb is the killer part.",
    },
    {
        "title": "Bohemian Rhapsody",
        "artist": "Queen",
        "genre": "Rock",
        "year": 1975,
        "difficulty": 5,
        "range_fit": ["tenor", "baritone", "alto", "soprano", "mezzo"],
        "notes": "Range monster. The 'Galileo' section is brutal but glorious.",
    },
    {
        "title": "We Will Rock You / We Are the Champions",
        "artist": "Queen",
        "genre": "Rock",
        "year": 1977,
        "difficulty": 3,
        "range_fit": ["baritone", "bass", "tenor", "alto"],
        "notes": "Crowd-pleaser, easy rhythm, the chorus needs some push.",
    },
    {
        "title": "Livin' on a Prayer",
        "artist": "Bon Jovi",
        "genre": "Rock",
        "year": 1986,
        "difficulty": 4,
        "range_fit": ["tenor", "soprano", "alto"],
        "notes": "That key change. High tenor belting required.",
    },
    {
        "title": "Sweet Caroline",
        "artist": "Neil Diamond",
        "genre": "Pop",
        "year": 1969,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto", "mezzo"],
        "notes": "The 'bump-bump-bump' is the whole point. Low difficulty, high fun.",
    },
    {
        "title": "Mr. Brightside",
        "artist": "The Killers",
        "genre": "Rock",
        "year": 2003,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "High-energy, sustained tenor, the crowd WILL sing along.",
    },
    {
        "title": "I Want It That Way",
        "artist": "Backstreet Boys",
        "genre": "Pop",
        "year": 1999,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "soprano"],
        "notes": "Harmonies optional but the lead sits comfortably mid-range.",
    },
    {
        "title": "Wonderwall",
        "artist": "Oasis",
        "genre": "Rock",
        "year": 1995,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Easy, chill, everyone knows it. Low range demands.",
    },
    {
        "title": "Creep",
        "artist": "Radiohead",
        "genre": "Rock",
        "year": 1992,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Quiet-loud dynamic. The 'run' section needs a leap up.",
    },
    {
        "title": "Sweet Home Alabama",
        "artist": "Lynyrd Skynyrd",
        "genre": "Rock",
        "year": 1974,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto"],
        "notes": "Comfortable southern rock range, easy sing-along.",
    },
    {
        "title": "Hotel California",
        "artist": "Eagles",
        "genre": "Rock",
        "year": 1976,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Moody and mid-tempo. Needs breath control on the long lines.",
    },
    {
        "title": "Total Eclipse of the Heart",
        "artist": "Bonnie Tyler",
        "genre": "Pop",
        "year": 1983,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Big dramatic build. Needs a strong upper-mid belt.",
    },
    {
        "title": "Pour Some Sugar On Me",
        "artist": "Def Leppard",
        "genre": "Rock",
        "year": 1987,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "High-energy glam rock. Strained high notes are part of the charm.",
    },
    {
        "title": "More Than a Feeling",
        "artist": "Boston",
        "genre": "Rock",
        "year": 1976,
        "difficulty": 4,
        "range_fit": ["tenor", "alto", "soprano"],
        "notes": "Soaring high tenor throughout. Not for the faint of lungs.",
    },
    {
        "title": "Africa",
        "artist": "Toto",
        "genre": "Rock",
        "year": 1982,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Smooth mid-range, the high 'bless the rains' is the test.",
    },

    # --- Pop / dance / diva ---
    {
        "title": "Wannabe",
        "artist": "Spice Girls",
        "genre": "Pop",
        "year": 1996,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Rapid-fire talk-singing. Low range demand, high energy demand.",
    },
    {
        "title": "...Baby One More Time",
        "artist": "Britney Spears",
        "genre": "Pop",
        "year": 1998,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Light mid-range pop. Easy to sing, fun crowd reaction.",
    },
    {
        "title": "Toxic",
        "artist": "Britney Spears",
        "genre": "Pop",
        "year": 2003,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Lower verses, breathy. Chorus jumps up a notch.",
    },
    {
        "title": "I Will Survive",
        "artist": "Gloria Gaynor",
        "genre": "Pop",
        "year": 1978,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Disco diva anthem. Needs sass and a decent belt on the chorus.",
    },
    {
        "title": "Dancing Queen",
        "artist": "ABBA",
        "genre": "Pop",
        "year": 1976,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Bright, sustained highs. ABBA harmonies are gorgeous if you attempt them.",
    },
    {
        "title": "Mamma Mia",
        "artist": "ABBA",
        "genre": "Pop",
        "year": 1975,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor", "baritone"],
        "notes": "Bouncy and forgiving. Great beginner pick.",
    },
    {
        "title": "I Wanna Dance with Somebody",
        "artist": "Whitney Houston",
        "genre": "Pop",
        "year": 1987,
        "difficulty": 5,
        "range_fit": ["soprano", "mezzo", "alto", "tenor"],
        "notes": "Whitney. Need we say more. Big-range belter.",
    },
    {
        "title": "Respect",
        "artist": "Aretha Franklin",
        "genre": "Soul",
        "year": 1967,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Soul belt with runs. The 'R-E-S-P-E-C-T' part is iconic and demanding.",
    },
    {
        "title": "(You Make Me Feel Like) A Natural Woman",
        "artist": "Aretha Franklin",
        "genre": "Soul",
        "year": 1967,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Gospel-tinged build. Needs dynamic control and a big final belt.",
    },
    {
        "title": "All Star",
        "artist": "Smash Mouth",
        "genre": "Rock",
        "year": 1999,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto", "bass"],
        "notes": "Punchy and easy. The Shrek song. Crowd always sings the 'HEY!'",
    },
    {
        "title": "Mr. Jones",
        "artist": "Counting Crows",
        "genre": "Rock",
        "year": 1993,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Talky mid-range verses, gentle chorus. Low difficulty.",
    },
    {
        "title": "Hey Jude",
        "artist": "The Beatles",
        "genre": "Rock",
        "year": 1968,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto", "mezzo"],
        "notes": "The 'na na na' is a 4-minute sing-along. Easy and communal.",
    },
    {
        "title": "Let It Be",
        "artist": "The Beatles",
        "genre": "Rock",
        "year": 1970,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Gentle, mid-range. Forgiving for beginners.",
    },
    {
        "title": "Sweet Child O' Mine",
        "artist": "Guns N' Roses",
        "genre": "Rock",
        "year": 1987,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Axl's high screech is the challenge. Embrace the strain or drop an octave.",
    },
    {
        "title": "Pour Some Sugar On Me",
        "artist": "Def Leppard",
        "genre": "Rock",
        "year": 1987,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "(duplicate-tagged intentionally omitted in production) High glam energy.",
    },
    {
        "title": "Zombie",
        "artist": "The Cranberries",
        "genre": "Rock",
        "year": 1994,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Dolores O'Riordan's keening wail is the whole song. Hard to match.",
    },
    {
        "title": "Mr. Brightside",
        "artist": "The Killers",
        "genre": "Rock",
        "year": 2003,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Already listed once — kept here once for the matcher; (de-dup at load).",
    },
    {
        "title": "Summer Nights",
        "artist": "Grease Cast",
        "genre": "Pop",
        "year": 1978,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto", "mezzo", "soprano"],
        "notes": "Duet-friendly, campy, easy. Great warm-up song.",
    },
    {
        "title": "Hopelessly Devoted to You",
        "artist": "Olivia Newton-John",
        "genre": "Pop",
        "year": 1978,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Tender ballad with a rising chorus. Needs breath support.",
    },
    {
        "title": "Building a Mystery",
        "artist": "Sarah McLachlan",
        "genre": "Pop",
        "year": 1997,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Husky mid-range verses, soaring chorus.",
    },
    {
        "title": "Son of a Preacher Man",
        "artist": "Dusty Springfield",
        "genre": "Soul",
        "year": 1968,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Smoky, low chest voice verses. Soulful mid belt on chorus.",
    },
    {
        "title": "Crazy in Love",
        "artist": "Beyoncé",
        "genre": "Pop",
        "year": 2003,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "High-energy diva pop. Horns + attitude + a tricky high bridge.",
    },
    {
        "title": "Halo",
        "artist": "Beyoncé",
        "genre": "Pop",
        "year": 2008,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Long sustained belt on 'halo'. Needs stamina and breath control.",
    },
    {
        "title": "Rolling in the Deep",
        "artist": "Adele",
        "genre": "Pop",
        "year": 2010,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Low chest verses, huge chorus belt. Adele range is demanding.",
    },
    {
        "title": "Someone Like You",
        "artist": "Adele",
        "genre": "Pop",
        "year": 2011,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Ballad, mostly mid-range, the high 'never mind' is the test.",
    },
    {
        "title": "Hello",
        "artist": "Adele",
        "genre": "Pop",
        "year": 2015,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Dramatic build from low chest to big belt. Demanding.",
    },
    {
        "title": "Valerie",
        "artist": "Amy Winehouse",
        "genre": "Soul",
        "year": 2006,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Soulful and laid-back. The 'why don't you come on over' needs lift.",
    },
    {
        "title": "Rehab",
        "artist": "Amy Winehouse",
        "genre": "Soul",
        "year": 2006,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Staccato retro-soul. Attitude matters more than range.",
    },
    {
        "title": "Superstition",
        "artist": "Stevie Wonder",
        "genre": "Soul",
        "year": 1972,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Groovy mid-range with some quick soul runs.",
    },
    {
        "title": "I Just Called to Say I Love You",
        "artist": "Stevie Wonder",
        "genre": "Soul",
        "year": 1984,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Gentle ballad, easy range, very singable.",
    },
    {
        "title": "Sir Duke",
        "artist": "Stevie Wonder",
        "genre": "Soul",
        "year": 1976,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Bouncy horn-line vocal. Fun and mid-difficulty.",
    },
    {
        "title": "Ain't No Mountain High Enough",
        "artist": "Marvin Gaye & Tammi Terrell",
        "genre": "Soul",
        "year": 1967,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo", "soprano"],
        "notes": "Classic duet. Both parts sit in comfortable mid-range with climbs.",
    },
    {
        "title": "I Heard It Through the Grapevine",
        "artist": "Marvin Gaye",
        "genre": "Soul",
        "year": 1968,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Moody soul. The repeated 'through the grapevine' needs stamina.",
    },
    {
        "title": "Stand By Me",
        "artist": "Ben E. King",
        "genre": "Soul",
        "year": 1961,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto", "mezzo"],
        "notes": "Timeless and easy. Forgiving range, gorgeous melody.",
    },
    {
        "title": "Under the Boardwalk",
        "artist": "The Drifters",
        "genre": "Soul",
        "year": 1964,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto"],
        "notes": "Breezy doo-wop, low difficulty, great warm-up.",
    },
    {
        "title": "My Girl",
        "artist": "The Temptations",
        "genre": "Soul",
        "year": 1964,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "bass", "alto"],
        "notes": "Smooth and easy. The bass lead is iconic and forgiving.",
    },
    {
        "title": "Proud Mary",
        "artist": "Tina Turner",
        "genre": "Soul",
        "year": 1970,
        "difficulty": 4,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Slow-then-fast. The 'rollin' section is high-energy belting.",
    },
    {
        "title": "What's Love Got to Do with It",
        "artist": "Tina Turner",
        "genre": "Pop",
        "year": 1984,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Husky mid-range, chorus lift. Attitude required.",
    },
    {
        "title": "9 to 5",
        "artist": "Dolly Parton",
        "genre": "Country",
        "year": 1980,
        "difficulty": 2,
        "range_fit": ["soprano", "mezzo", "alto", "tenor"],
        "notes": "Upbeat country-pop. Bright, easy range.",
    },
    {
        "title": "Jolene",
        "artist": "Dolly Parton",
        "genre": "Country",
        "year": 1973,
        "difficulty": 3,
        "range_fit": ["soprano", "mezzo", "alto", "tenor"],
        "notes": "Sustained high pleading 'Jolene'. Needs breath and emotion.",
    },
    {
        "title": "Friends in Low Places",
        "artist": "Garth Brooks",
        "genre": "Country",
        "year": 1990,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto"],
        "notes": "The ultimate country sing-along. Easy and rowdy.",
    },
    {
        "title": "Wagon Wheel",
        "artist": "Old Crow Medicine Show",
        "genre": "Country",
        "year": 2004,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "bass", "alto", "mezzo"],
        "notes": "Crowd-favorite folk-country. Forgiving range, big chorus.",
    },
    {
        "title": "Ring of Fire",
        "artist": "Johnny Cash",
        "genre": "Country",
        "year": 1963,
        "difficulty": 1,
        "range_fit": ["bass", "baritone", "tenor", "alto"],
        "notes": "Low and steady. The most forgiving song on this list.",
    },
    {
        "title": "Folsom Prison Blues",
        "artist": "Johnny Cash",
        "genre": "Country",
        "year": 1968,
        "difficulty": 1,
        "range_fit": ["bass", "baritone", "tenor", "alto"],
        "notes": "Talk-sing in a low register. Easiest song ever for low voices.",
    },
    {
        "title": "Man! I Feel Like a Woman!",
        "artist": "Shania Twain",
        "genre": "Country",
        "year": 1997,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Sassy country-pop with a high-energy chorus.",
    },
    {
        "title": "Friends in Low Places",
        "artist": "Garth Brooks",
        "genre": "Country",
        "year": 1990,
        "difficulty": 2,
        "range_fit": ["baritone", "bass", "tenor", "alto"],
        "notes": "Already in list above — will be de-duplicated at load.",
    },
    {
        "title": "Waterloo",
        "artist": "ABBA",
        "genre": "Pop",
        "year": 1974,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Bouncy Eurovision energy. Easy and fun.",
    },
    {
        "title": "Knowing Me, Knowing You",
        "artist": "ABBA",
        "genre": "Pop",
        "year": 1976,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Melancholy ABBA. Mid-range with a few lifts.",
    },
    {
        "title": "Mr. Saxobeat",
        "artist": "Alexandra Stan",
        "genre": "Pop",
        "year": 2011,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano"],
        "notes": "Dance-pop, repetitive, easy range, fun energy.",
    },
    {
        "title": "Call Me Maybe",
        "artist": "Carly Rae Jepsen",
        "genre": "Pop",
        "year": 2012,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Bubblegum pop, catchy, low difficulty, big crowd sing.",
    },
    {
        "title": "Shake It Off",
        "artist": "Taylor Swift",
        "genre": "Pop",
        "year": 2014,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Upbeat, talk-sing verses, easy chorus. Great warm-up.",
    },
    {
        "title": "Blank Space",
        "artist": "Taylor Swift",
        "genre": "Pop",
        "year": 2014,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Spat-out verses, soaring chorus. Forgiving mid-range.",
    },
    {
        "title": "Uptown Funk",
        "artist": "Mark Ronson ft. Bruno Mars",
        "genre": "Pop",
        "year": 2014,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Funk energy, talk-sing staccato, the high 'hot damn' needs push.",
    },
    {
        "title": "24K Magic",
        "artist": "Bruno Mars",
        "genre": "Pop",
        "year": 2016,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Funk-pop, falsetto hooks, mid difficulty.",
    },
    {
        "title": "Just the Way You Are",
        "artist": "Bruno Mars",
        "genre": "Pop",
        "year": 2010,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Smooth ballad, easy range, crowd-pleaser.",
    },
    {
        "title": "Don't Stop Me Now",
        "artist": "Queen",
        "genre": "Rock",
        "year": 1978,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto", "soprano", "mezzo"],
        "notes": "Joyful and relentless. Freddie's high jumps are the challenge.",
    },
    {
        "title": "Somebody to Love",
        "artist": "Queen",
        "genre": "Rock",
        "year": 1976,
        "difficulty": 5,
        "range_fit": ["tenor", "baritone", "alto", "soprano", "mezzo"],
        "notes": "Gospel-queen. Wide range, choir harmonies, very demanding.",
    },
    {
        "title": "Fat Bottomed Girls",
        "artist": "Queen",
        "genre": "Rock",
        "year": 1978,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "bass", "alto"],
        "notes": "Campy arena rock, big chorus, easy rhythm.",
    },
    {
        "title": "Bennie and the Jets",
        "artist": "Elton John",
        "genre": "Pop",
        "year": 1974,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Elton's mid-tenor. The 'B-B-B-Bennie' is the fun part.",
    },
    {
        "title": "Tiny Dancer",
        "artist": "Elton John",
        "genre": "Pop",
        "year": 1971,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Gentle build to a big chorus. Needs breath control.",
    },
    {
        "title": "Rocket Man",
        "artist": "Elton John",
        "genre": "Pop",
        "year": 1972,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Moody, mid-range, the 'high' on 'I think it's gonna be a long long time' is the test.",
    },
    {
        "title": "Crocodile Rock",
        "artist": "Elton John",
        "genre": "Pop",
        "year": 1972,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo", "soprano"],
        "notes": "Bouncy retro-pop, the 'la-la-las' are a workout.",
    },
    {
        "title": "Piano Man",
        "artist": "Billy Joel",
        "genre": "Pop",
        "year": 1973,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto", "mezzo"],
        "notes": "Storyteller baritone. The 'sing us a song' is a communal moment.",
    },
    {
        "title": "Uptown Girl",
        "artist": "Billy Joel",
        "genre": "Pop",
        "year": 1983,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo", "soprano"],
        "notes": "Doo-wop bounce, the high 'uptown girl' needs a leap.",
    },
    {
        "title": "We Didn't Start the Fire",
        "artist": "Billy Joel",
        "genre": "Pop",
        "year": 1989,
        "difficulty": 3,
        "range_fit": ["baritone", "tenor", "alto", "mezzo"],
        "notes": "Rapid-fire history lesson. Memorization is the hard part, not range.",
    },
    {
        "title": "I Love Rock 'n' Roll",
        "artist": "Joan Jett",
        "genre": "Rock",
        "year": 1981,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "tenor", "baritone"],
        "notes": "Punchy, low-difficulty anthem. Easy and satisfying.",
    },
    {
        "title": "Bad Romance",
        "artist": "Lady Gaga",
        "genre": "Pop",
        "year": 2009,
        "difficulty": 3,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Dramatic electropop. The 'rah-rah' hook + chorus belt.",
    },
    {
        "title": "Shallow",
        "artist": "Lady Gaga & Bradley Cooper",
        "genre": "Pop",
        "year": 2018,
        "difficulty": 5,
        "range_fit": ["tenor", "baritone", "alto", "mezzo", "soprano"],
        "notes": "Duet with a HUGE final belt. The 'ahhhh' is the moment.",
    },
    {
        "title": "Poker Face",
        "artist": "Lady Gaga",
        "genre": "Pop",
        "year": 2008,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Talk-sing electropop. Low range demand, high attitude demand.",
    },
    {
        "title": "Sweet Dreams",
        "artist": "Eurythmics",
        "genre": "Pop",
        "year": 1983,
        "difficulty": 2,
        "range_fit": ["alto", "mezzo", "soprano", "tenor"],
        "notes": "Moody synth-pop. Repetitive, easy range.",
    },
    {
        "title": "Take On Me",
        "artist": "a-ha",
        "genre": "Pop",
        "year": 1984,
        "difficulty": 5,
        "range_fit": ["tenor", "alto", "soprano"],
        "notes": "That impossibly high 'in a day or two'. Range killer.",
    },
    {
        "title": "Don't You (Forget About Me)",
        "artist": "Simple Minds",
        "genre": "Rock",
        "year": 1985,
        "difficulty": 3,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Breakfast Club anthem. Mid-range, big feel-good chorus.",
    },
    {
        "title": "Summer of '69",
        "artist": "Bryan Adams",
        "genre": "Rock",
        "year": 1985,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Raspy mid-range rock. Easy and nostalgic.",
    },
    {
        "title": "(Everything I Do) I Do It for You",
        "artist": "Bryan Adams",
        "genre": "Pop",
        "year": 1991,
        "difficulty": 3,
        "range_fit": ["baritone", "tenor", "alto", "mezzo"],
        "notes": "Ballad with a soaring chorus. Needs breath and a bit of belt.",
    },
    {
        "title": "Living on a Prayer",
        "artist": "Bon Jovi",
        "genre": "Rock",
        "year": 1986,
        "difficulty": 4,
        "range_fit": ["tenor", "soprano", "alto"],
        "notes": "Duplicate-tagged for matcher testing; de-dup at load.",
    },
    {
        "title": "It's My Life",
        "artist": "Bon Jovi",
        "genre": "Rock",
        "year": 2000,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Anthemic, mid-range, easy to belt the chorus.",
    },
    {
        "title": "Closing Time",
        "artist": "Semisonic",
        "genre": "Rock",
        "year": 1998,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Easy last-song-of-the-night. Forgiving range.",
    },
    {
        "title": "Semi-Charmed Life",
        "artist": "Third Eye Blind",
        "genre": "Rock",
        "year": 1997,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Rapid verses, bouncy chorus. Energy > range.",
    },
    {
        "title": "Under Pressure",
        "artist": "Queen & David Bowie",
        "genre": "Rock",
        "year": 1981,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto", "soprano", "mezzo"],
        "notes": "Rangey duet. The 'this is our last dance' climb is the test.",
    },
    {
        "title": "Rebel Rebel",
        "artist": "David Bowie",
        "genre": "Rock",
        "year": 1974,
        "difficulty": 2,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Glam stomp, easy range, big attitude.",
    },
    {
        "title": "Heroes",
        "artist": "David Bowie",
        "genre": "Rock",
        "year": 1977,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Builds from low to soaring. Needs dynamic control.",
    },
    {
        "title": "Come As You Are",
        "artist": "Nirvana",
        "genre": "Rock",
        "year": 1992,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Moody, mid-range, easy. The 'memoria' mumble is forgiving.",
    },
    {
        "title": "Smells Like Teen Spirit",
        "artist": "Nirvana",
        "genre": "Rock",
        "year": 1991,
        "difficulty": 3,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Quiet-loud. The 'with the lights out' belt needs push.",
    },
    {
        "title": "Black Hole Sun",
        "artist": "Soundgarden",
        "genre": "Rock",
        "year": 1994,
        "difficulty": 4,
        "range_fit": ["tenor", "baritone", "alto"],
        "notes": "Chris Cornell range. Demanding high baritone / low tenor.",
    },
    {
        "title": "Creep",
        "artist": "Radiohead",
        "genre": "Rock",
        "year": 1992,
        "difficulty": 3,
        "range_fit": ["tenor", "baritone", "alto", "mezzo"],
        "notes": "Already in list — kept once at load.",
    },
    {
        "title": "Loser",
        "artist": "Beck",
        "genre": "Rock",
        "year": 1993,
        "difficulty": 2,
        "range_fit": ["baritone", "tenor", "alto"],
        "notes": "Slacker talk-rap. Lowest difficulty, high irony.",
    },
]
